name: EAS Build
on:
  push:
    branches:
      - main
    paths:
      - 'EmployeeManagementSystem/ems-frontendNative/**'

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'EmployeeManagementSystem/ems-frontendNative/package-lock.json'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: EmployeeManagementSystem/ems-frontendNative
        run: npm install --legacy-peer-deps

      - name: 🚀 Build APK
        working-directory: EmployeeManagementSystem/ems-frontendNative
        run: eas build --platform android --profile preview --non-interactive
